- name: Fix SSH Connectivity
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: Create SSH directory if not exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'
    - name: Create known_hosts in Ansible controller if not exists
      file:
        path: ~/.ssh/known_hosts
        state: touch
        mode: u=rw,g=r,o=r
    - name: Delete SSH Known hosts
      shell: ssh-keygen -f ~/.ssh/known_hosts -R {{ hostvars[item]['ansible_host'] }}
      with_items:
        - "{{ groups['all'] }}"
    - name: Scan SSH Known hosts
      shell: ssh-keyscan -H {{ hostvars[item]['ansible_host'] }} >> ~/.ssh/known_hosts
      with_items:
        - "{{ groups['all'] }}"
- name: Ping test
  hosts: all
  tasks:
    - name: Ping test
      ping: