- 
  name: Set selinux to permissive
  hosts: mongodb_servers
  tasks:
    - name: Set selinux to permissive
      selinux: 
        policy: targeted
        state: permissive
-
  name: Install Percona Server for MongoDB and related troubleshooting tools
  hosts: mongodb_servers
  vars: 
    percona_packages:
      - percona-server-mongodb
      - percona-server-mongodb-server
      - percona-server-mongodb-shell
      - percona-server-mongodb-tools
    troubleshooting_packages:
      - net-tools
      - openldap-clients
      - bind-utils
  tasks:
    - name: Import Percona Packaging Key
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/PERCONA-PACKAGING-KEY
    - name: Import Percona GPG Key
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona
    - name: Install troubleshooting packages
      yum:
        name: "https://repo.percona.com/prel/yum/release/8.0/RPMS/x86_64/percona-release-1.0-27.noarch.rpm"
        state: present
    - name: Setup MongoDB 5.0 repository
      shell: percona-release setup psmdb50 -y
    - name: Percona Packages
      yum:
        name: "{{ percona_packages }}"
        state: present
    - name: Troubleshooting Packages
      yum:
        name: "{{ troubleshooting_packages }}"
        state: present
-
  name: Start MongoDB and enable MongoDB
  hosts: mongodb_servers
  tasks:
    - name: Start mongod service
      service:
        name: mongod
        state: started
    - name: Autostart mongod service
      service:  
        name: mongod
        enabled: yes
-
  name: Copy MongoDB certificates
  hosts: mongodb_servers
  tasks:
    - name: Create a directory /var/lib/mongocerts
      file:
        path: /var/lib/mongocerts
        state: directory
        mode: '0755'
        owner: mongod
        group: mongod
    - name: Copy /vagrant/ssl/pem/ca-bundle.pem to /var/lib/mongocerts/ca-bundle.pem
      copy: 
        src: /vagrant/ssl/pem/ca-bundle.pem
        dest: /var/lib/mongocerts/ca-bundle.pem
        remote_src: yes
        mode: '0600'
        owner: mongod
        group: mongod  
    - name: Copy MongoDB certificates
      shell: cp -v /vagrant/ssl/pem/mongod* /var/lib/mongocerts/
    - name: Copy MongoDB User certificates
      shell: cp -v /vagrant/ssl/mongodb/* /var/lib/mongocerts/
    - name: Change ownership of mongod certificates to mongod
      shell: chown mongod:mongod /var/lib/mongocerts/*
    - name: Change permissions of mongod certificates
      shell: chmod 600 /var/lib/mongocerts/*      
   
- name: Set DNS to use Samba service
  hosts: mongodb_servers
  tasks:
    - name: Disable DNS via Networking manager
      shell: echo -e "[main]\ndns=none" > /etc/NetworkManager/conf.d/90-dns-none.conf
      args:
        creates: /etc/NetworkManager/conf.d/90-dns-none.conf
    - name: Restart Networking
      service:
        name: NetworkManager 
        state: restarted
    - name: Remove resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent
    - name: Create empty resolv.conf
      file:
        path: /etc/resolv.conf
        state: touch
    - name: Append DNS1 entry to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: nameserver 192.168.56.51