- 
  name: Set selinux to permissive
  hosts: mysql_servers
  tasks:
    - name: Set selinux to permissive
      selinux: 
        policy: targeted
        state: permissive
-
  name: Install Percona Server for MySQL and related troubleshooting tools
  hosts: mysql_servers
  vars: 
    percona_packages:
      - percona-server-server
      - percona-server-shared
      - percona-server-client
    troubleshooting_packages:
      - net-tools
      - openldap-clients
      - bind-utils
  tasks:
    - name: Import Percona Packaging Key
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/PERCONA-PACKAGING-KEY
    - name: Import Percona GPG Key
      rpm_key:
        state: present
        key: https://repo.percona.com/yum/RPM-GPG-KEY-Percona
    - name: Install troubleshooting packages
      yum:
        name: "https://repo.percona.com/prel/yum/release/8.0/RPMS/x86_64/percona-release-1.0-27.noarch.rpm"
        state: present
    - name: Setup Percona 8.0 repository
      shell: percona-release setup ps-80 -y
    - name: Percona Packages
      yum:
        name: "{{ percona_packages }}"
        state: present
    - name: Troubleshooting Packages
      yum:
        name: "{{ troubleshooting_packages }}"
        state: present
-
  name: Copy MySQL certificates
  hosts: mysql_servers
  tasks:
    - name: Create a directory /var/lib/mysqlcerts
      file:
        path: /var/lib/mysqlcerts
        state: directory
        mode: '0755'
        owner: mysql
        group: mysql
    - name: Copy /vagrant/ssl/pem/ca-bundle.pem to /var/lib/mysqlcerts/ca-bundle.pem
      copy: 
        src: /vagrant/ssl/pem/ca-bundle.pem
        dest: /var/lib/mysqlcerts/ca-bundle.pem
        remote_src: yes
        mode: '0600'
        owner: mysql
        group: mysql  
    - name: Copy MySQL certificates
      shell: cp -v /vagrant/ssl/pem/mysql* /var/lib/mysqlcerts/
    - name: Change ownership of MySQL certificates to mysql
      shell: chown mysql:mysql /var/lib/mysqlcerts/*
    - name: Change permissions of MySQL certificates
      shell: chmod 600 /var/lib/mysqlcerts/*      
-
  name: Start MySQL
  hosts: mysql_servers
  tasks:
    - name: Initialize MySQL data directory
      shell: mysqld --initialize-insecure --user=mysql
      args:
        creates: /var/lib/mysql/ibdata1
    - name: Start MySQL service
      service:
        name: mysql
        state: started
    - name: Autostart MySQL service
      service:  
        name: mysql
        enabled: yes

- name: Set DNS to use Samba service
  hosts: mysql_servers
  tasks:
    - name: Disable DNS via Networking manager
      shell: echo -e "[main]\ndns=none" > /etc/NetworkManager/conf.d/90-dns-none.conf
      args:
        creates: /etc/NetworkManager/conf.d/90-dns-none.conf
    - name: Restart Networking
      service:
        name: NetworkManager 
        state: restarted
    - name: Remove resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent
    - name: Create empty resolv.conf
      file:
        path: /etc/resolv.conf
        state: touch
    - name: Append DNS1 entry to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: nameserver 192.168.56.51